### ISSUE TITLE
Maximize practicability of Kademlia

### ISSUE THREAD

**Issue by kfangw** [planetarium/libplanet#1363]
## Backgrounds
Kademlia assumes that

0. A node sends a message to a group expecting at least one node of the group receives the message. A node groups nodes into logN number of groups according to the distance. refer to https://github.com/limebell/Kademlia

1. Enough number of intact nodes required. 
When an intact node received a message then it broadcast back to the network by the rule 0.

2. A node has reachability to all groups. 
At least one node from any group can be reachable from another node that sending a message.

In practice, assumptions 1 and 2 cannot be guaranteed.
Hence, heuristics needed to maximize the assumptions.

## Heuristics
For assumption 1:
Send a message to multiple nodes which belong to the group to minimize the opportunity of dropping the message for the group.

For assumption 2:
Gathering peers as many as possible to maximize the reachability.
If the address is 20 bytes then, the number of groups is 160. A node would be better to know at least one peer for a group. It means that a node does not need to keep a fat group(containing 2+ nodes).

For assumption 0, 2:
For 20 bytes address space, a node should be able to broadcast a message to at least 16 peers(representatives for each group). 
Without a doubt, a node may not keeps reachability to every group. Although, a node needs to maximize deliverability and keep the minimum number of peers to be broadcasted.

## Implementations
1. Select 2+ peers from a bucket(group) and increase minimum peers from 10 to 16
2. Revise peer exchange logic and routing table to support assumption 2.

**Comment by limebell** [comment]
Thank you for the discussion. I would like to add 1 more heuristic assumption.

In libplanet, peer discovery process discovers maximum depth of 3 in order to reduce total operation time. This may leads to problem that the closest node in the network is not added to the routing table. It would be great if we can resolve this problem somedays :)

Additionally, it would be great to select "closer" peers in higher priority when selecting to fill up 16 peers. Now it selects from very first peer, which is the "farther".

**Comment by kfangw** [comment]
>Additionally, it would be great to select "closer" peers in higher priority when selecting to fill up 16 peers. Now it selects from very first peer, which is the "farther".

Agreed. If there is a chance to fill up 16+ peers from buckets, not to be selected randomly, the rule should be followed. 

>In libplanet, peer discovery process discovers maximum depth of 3 in order to reduce total operation time

I am suspicious about the overhead of peer discovery and exchange(hereafter call it pex). IMHO, The load may relatively lighter than other message exchanges.
Furthermore, I think that It would be better to trigger the peer discovery by events, not only by the timer. The event may be one of following
- drop a peer from the table
- freshly launched node
- incoming message from an unknown peer ( I am not sure it can happen in the current implementation of libplanet)

The routing table should be growing up continuously and dynamically to meet assumption 2. It is the most important constraint I think.

**Comment by greymistcube** [comment]
> In libplanet, peer discovery process discovers maximum depth of 3 in order to reduce total operation time.

> I am suspicious about the overhead of peer discovery and exchange(hereafter call it pex).

Seems like the original formulation of Kademlia does not limit depth for peer discovery but only concurrency. Since peer discovery doesn't propagate messages throughout the network (i.e., hopping nodes), overall overhead might not be too severe. We could update the recursion termination condition to simply be non-decreased minimum distance from the target after iteration.

**Comment by greymistcube** [comment]
https://en.wikipedia.org/wiki/Kademlia#Joining_the_network

> After this, the joining node refreshes all k-buckets further away than the k-bucket the bootstrap node falls in. This refresh is just a lookup of a random key that is within that k-bucket range.

On a side note, I might not have parsed through the code enough, but there doesn't seem to be a full k-buckets update with random address lookups during the bootstrapping phase. If this is missing, it might adversely affect the network topology.
