### ISSUE TITLE
Introduce an easy way to get peer string for `Swarm<T>.BootstrapAsync()`

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#1934]
`BoundPeer.ToString()` returns [`Address`.`EndPoint`.`PublicIPAddress`](https://github.com/planetarium/libplanet/blob/515dbe10fc1f92db1781432f82dd05941796aa1c/Libplanet.Net/BoundPeer.cs#L159) (e.g. `"0x7d904Bf4A84A92e7C4f976369361aD834b7dCA5a.Unspecified/localhost:31234."`). 

but we need to its public key to create `BoundPeer` directly. (Even `BoundPeer` has a factory method `.ParsePeer()` which creates from an already formatted string. 😇 )

**Comment by greymistcube** [comment]
Just to elaborate and give it more context, this heavily depends on the running context.

- Is `PrivateKey` provided?
- Is `Swarm<T>` using `host` or `iceServers`?
  - If `Swarm<T>` is using `host`, is `port` provided?

The earliest stage as to when we can obtain the peer string for each combination is as follows:
- `PrivateKey`, `host`, and `port` are all provided: Before `Swarm<T>` instantiation.
- All other possible combinations: After `Swarm<T>.BootstrapAsync()`.

The latter is due to binding happening at unnecessarily late, and I mean **really** late, during `Swarm<T>.StartAsync()` phase, although this is probably possible during `Swarm<T>()`. This is due to a design flaw, and to properly resolve this issue, #1612 must be resolved first. 🙄

As we have discussed, as for needing it only for development/deployment purpose of getting a fixed seed peer string, this **should not** require an `Swarm<T>` instance anyway as the decision for what `Swarm<T>`'s `BoundPeer` should be is being made at a higher level. I'll be putting in a quick and dirty method somewhere under `Libplanet.Node`. 😗

**Comment by greymistcube** [comment]
Rudimentary functionality implemented in [UniLibplanet](https://github.com/planetarium/UniLibplanet).
