### ISSUE TITLE
Fix SwarmBenchmark IndexOutOfRangeException Error

### ISSUE THREAD

**Issue by Atralupus** [planetarium/libplanet#1965]
Detail log: https://github.com/planetarium/libplanet/runs/5986779803?check_suite_focus=true
<img width="1450" alt="스크린샷 2022-05-16 오후 1 47 23" src="https://user-images.githubusercontent.com/30599098/168521604-e052ae69-1b39-4206-9430-b00f67518d04.png">

seems to be a problem here
```csharp
// Libplanet.Tests/TestUtils.cs 39 line
public static readonly PrivateKey[] AdjacentKeys = new PrivateKey[10]
```

**Comment by kasumielf** [comment]
I was discover this bug not a caused by PrivateKey Array. When I attach to debug, IndexOutOfRangeException was excepted from https://github.com/planetarium/libplanet/blob/e19221ab6e59f07684c58b1f68f6ea8247a61f48/Libplanet.Benchmarks/SwarmBenchmark.cs#L62.

I'd fix this issue but not a make PR yet because SwarmBenchmark takes too much running times(over 10~15 minutes.) when I ran it.

I'm not sure this situation is not a specific. If it have no problem, I'll make PR.
