### ISSUE TITLE
`IActionContext.GenesisHash` property

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1972]
Currently there is no way to determine which network/chain it belongs to and runs in inside `IAction.Execute()` method.  As Libplanet identify networks/chains using their genesis block, it would be useful if `IActionAction` has a property containing chain's genesis hash, supposing `IActionContext.GenesisHash`.

**Comment by hunkim98** [comment]
✋ I would like to try this out

**Comment by akaz00** [comment]
✋

**Comment by longfin** [comment]
To accomplish this issue, there are a few things you need to know 😅 
(Everything written below is based on [Libplanet 0.39.0](https://github.com/planetarium/libplanet/releases/tag/0.39.0).)

# About genesis hash

- The genesis hash as the name suggests, stands for the block hash (`Block<T>.Hash`) of the genesis block. 
- There is only one genesis block per chain and can be obtained from the `BlockChain<T>.GenesisBlock` field. 

# Injecting `IActionContext` on `IAction.Execute()`

- `IActionContext` is an data interface of context for action executing(i.e., `IAction.Execute()`).
- All actions in the block(`Block<T>`) are evaluated on [`ActionEvaluator<T>.EvaluateActions()` method ](https://github.com/planetarium/libplanet/blob/0.39.0/Libplanet/Action/ActionEvaluator.cs#L280).
  - Therefore, `IActionContext` for actions also will be created [in that method](https://github.com/planetarium/libplanet/blob/0.39.0/Libplanet/Action/ActionEvaluator.cs#L245-L257).


# Strategies

- One possible option is, injecting `Block<T>.Hash` of `BlockChain<T>.GenesisBlock` to the constructor of `ActionEvalutor()` and storing it as a private field on `ActionEvalautor`.
  - `ActionEvalautor` is created on [`BlockChain<T>`'s constructor](https://github.com/planetarium/libplanet/blob/989faeb37fbeb2508a1b2147ef4ed837296e3219/Libplanet/Blockchain/BlockChain.cs#L166-L170). so you can easily add it there.
  - It can seem that a strange act to inject the genesis hash before evaluating the block. but I think it's okay because the genesis block can be treated as the source of consensus. (I haven't thought about it very deeply, so if you have any comments, please. @planetarium/libplanet )
- Another option is, adding the genesis hash as an argument to all internal methods up to `ActionEvaluator<T>.EvaluateActions()` , and modifing it to be called by the interface(i.e., `ActionEvalautor<T>.Evaluate()`).
  - `ActionEvalautor<T>.Evaluate()` is called on [`BlockChain<T>.ExecuteActions()` method](https://github.com/planetarium/libplanet/blob/989faeb37fbeb2508a1b2147ef4ed837296e3219/Libplanet/Blockchain/BlockChain.cs#L787-L790).
- IMHO, Because the scope for change is small, the first option looks a bit better, unless for some other reason.
