### ISSUE TITLE
Find 2 or 3 C# library of BLS cryptography.

### ISSUE THREAD

**Issue by riemannulus** [planetarium/libplanet#3595]

**Comment by riemannulus** [comment]
I found 
- https://github.com/NethermindEth/cortex-cryptography-bls
- https://github.com/herumi/bls/tree/master/ffi/cs

**Comment by OnedgeLee** [comment]
Since [cortex-cryptography-bls](https://github.com/NethermindEth/cortex-cryptography-bls) uses [herumi-bls](https://github.com/herumi/bls/tree/master/ffi/cs), both are fundamentally same,
Another option is [blst-bls](https://github.com/supranational/blst), and according to [this reference](https://github.com/AlexiaChen/benchmarks-bls-libs), blst-bls seems better for performance.
geth selectively uses both implementation, so it seems like both of them are stable.

**Comment by riemannulus** [comment]
https://github.com/planetarium/libplanet/issues/3594#issuecomment-2008572918 Close.
