### ISSUE TITLE
💔 Report problem of Libplanet.Explorer GraphQL schema changes

### ISSUE THREAD

**Issue by riemannulus** [planetarium/libplanet#3656]
# Context
Since https://github.com/planetarium/libplanet/releases/tag/3.9.3 and https://github.com/planetarium/libplanet/releases/tag/3.9.4, `Libplanet.Explorer` schema is changed. But it causes problems for other external services that use the `Libplanet.Explorer` query type. 

Please report to comment with problem details and repository URLs.

**Comment by U-lis** [comment]
When using `TransactionResult` query, the response type has been changed from `TxResultType` to `TxResult`.
This causes IAP and SeasonPass service to not to fetch transaction result and update to DB.

**Comment by greymistcube** [comment]
@U-lis Can it be resolved by changing `TxResultType` to `TxResult`? It was a mistake to not have a name for the type defined and use auto generated name `TxResultType` in the first place (all other types already had names defined). The overall schema needs to be updated due to additional types being defined and/or being changed (like `BlockHash` no longer being an `ID` but its own type, etc.)

**Comment by U-lis** [comment]
> @U-lis Can it be resolved by changing `TxResultType` to `TxResult`? It was a mistake to not have a name for the type defined and use auto generated name `TxResultType` in the first place (all other types already had names defined). The overall schema needs to be updated due to additional types being defined and/or being changed (like `BlockHash` no longer being an `ID` but its own type, etc.)

Yes, this issue can be resolved by changing `TxResultType` to `TxResult` in query. Then I'll update type name to newer one.

**Comment by greymistcube** [comment]
@U-lis Since there are too many changes to account for, we'll try to roll back changes and release 4.0.3.

**Comment by riemannulus** [comment]
Rollback all schema. closed this issues
