### ISSUE TITLE
Prevent selfish mining

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#546]

**Comment by limebell** [comment]
Let's assume two miners A and B.
Miner A is based on a legit client, so tries to put all transaction that are staged. But miner B uses illegal client and it ignores all transactions that are staged.
Currently block mining time is proportional to number of containing transactions, block with no transactions will be mined first in many cases.
Since block mining can be canceled, block with no transaction will be only block to be appended on the blockchain. We need to find a way to prevent this situation to be happened.

**Comment by kijun** [comment]
One possibility is to scale mining reward based on the number of transactions inside each block.
