### ISSUE TITLE
Introduce Span<T> to StunMessage

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#603]
## Context

After C# 7.2 & [System.Memory], `Span<T>` was introduced to reduce heap allocation. It would be great if we can apply it to `StunMessage`'s parsing process to improve performance.

[System.Memory]: https://www.nuget.org/packages/System.Memory/

## Tips

- Because .netstandard2.0 doesn't support `Stream.ReadAsync(Memory<T>)` and `Stream.ReadAsync(Span<T>)`, you'll need to branch through a preprocessor. Then [this MSDN docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives) will be helpful.

**Comment by moreal** [comment]
As you said, C# 7.2 introduced `Memory<T>`, `Span<T>` and they help memory management effect But it seems not to support `Stream.ReadAsync(Memory<T>)`, `Stream.ReadAsync(Span<T>)`. There is only `Stream.ReadAsync(byte[])` in *.netstandard2.0*.
Futrhermore, *Libplanet* target multiple frameworks, *.netcoreapp3.0* and *.netstandard2.0*.

I tried this, but it couldn't be applied sadly because of them.

**Comment by OnedgeLee** [comment]
@longfin May I close this issue?
As @moreal mentioned, seems like dotnet does not support  `Stream.ReadAsync(Span<T>)` at all. (only `Stream.ReadAsync(Memory<T>)` is available.)

**Comment by longfin** [comment]
Sure.
