### ISSUE TITLE
Links to GitHub source code in the docs seem broken

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#82]
Source links in documentation page seem to broken. (e.g. [link](https://github.com/planetarium/libplanet.net/blob/merge/Libplanet/Address.cs/#L94) in [`Libplanet.Address`](https://planetarium.github.io/libplanet.net/pulls/54/api/Libplanet.Address.html))

**Comment by dahlia** [comment]
This bug is even more complicated in recent builds: <https://planetarium.github.io/libplanet.net/master/api/Libplanet.Address.html>.  The generated `href` is like: <https://github.com/planetarium/libplanet.net/blob/master/Libplanet/obj/Release/netstandard2.0/g/EqualityGenerator/Address_17837EF5.g.cs/#L11>.  It seems because Uno.CodeGen generates partial files under the hood.
